version: '3.9'

services:
  db:
    image: 'postgres'
    environment: 
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes

  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: lebkovy/backend
    volumes:
      - ./backend:/opt/app
      - /opt/app/node_modules
    environment:
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'docker'
      CHOKIDAR_USEPOOLING: 'true'
    ports:
      - '5000:4000'

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules
    tty: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '9090:80'



volumes:
  data:

