version: '3.9'

services:
  db:
    image: 'postgres'
    environment: 
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes

  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: lebkovy/backend
    volumes:
      - ./:/app
      - /opt/app/node_modules
    environment:
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'docker'
    ports:
      - '5000:4000'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '9090:80'

  frontend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /opt/app/node_modules
      - ./frontend:/opt/app

volumes:
  data:

