version: '3.9'

services: 
  server:
    build: .
    image: lebkovy/backend_server
    volumes:
      - ./:/app
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    environment: 
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  data:

