apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendlb-deployment
  labels:
    app: app
    component: backend
spec:
  template:
    metadata:
      name: backendlb-pod
      labels:
        component: backend
        app: app
    spec:
      containers:
        - name: backendlb-container
          image: lebkovy/backend
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PGPASSWORD
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PGDATABASE
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PGUSER
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PGHOST
            - name: REDIS_HOST
              value: redis-clusterip
            - name: REDIS_PORT
              value: '6379'
  replicas: 3
  selector:
    matchLabels:
      app: app
      component: backend
